const glossaryGroupMap = new Map();
const rawMap = new Map();

rawMap.set("AWS", { title: "Amazon Web Services", groups: ["aws", "cloud"]});
rawMap.set("AMI", { title: "Amazon Machine Image", groups: ["aws"]});
rawMap.set("ARN", { title: "Amazon Resource Name", groups: ["aws"]});
rawMap.set("AmazonEC2", { title: "Amazon Elastic Compute Cloud", th: "Amazon EC2", groups: ["aws"], classes: ["nowrap"]});
rawMap.set("AmazonECS", { title: "Amazon Elastic Container Service", th: "Amazon ECS", groups: ["aws"], classes: [["skip", "nowrap"]]});
rawMap.set("AmazonEKS", { title: "Amazon Elastic Kubernetes Service", th: "Amazon EKS", groups: ["aws"], classes: [["skip", "nowrap"]], notes: "#K8s"});
rawMap.set("AmazonS3", { title: "Amazon Simple Storage Service", th: "Amazon S3", groups: ["aws"], classes: [["skip", "nowrap"]]});
rawMap.set("AmazonEBS", { title: "Amazon Elastic Block Storage", th: "Amazon EBS", groups: ["aws"], classes: [["skip", "nowrap"]]});
rawMap.set("AmazonEFS", { title: "Amazon Elastic File Storage", th: "Amazon EFS", groups: ["aws"], classes: [["skip", "nowrap"]]});
rawMap.set("AmazonFSx", { html: [{text: "Amazon File Storage for "}, {tag: "b", text: "x"}], th: "Amazon FSx", groups: ["aws"], classes: [["skip", "nowrap"]]});
rawMap.set("AmazonVPC", { title: "Amazon Virtual Private Cloud", th: "Amazon VPC", groups: ["aws"], classes: [["skip", "nowrap"]]});
rawMap.set("AmazonQLDB", { title: "Amazon Quantum Ledger Database", th: "Amazon QLDB", groups: ["aws"], classes: [["skip", "nowrap"]]});
rawMap.set("AmazonRDS", { title: "Amazon Relational Database Service", th: "Amazon RDS", groups: ["aws"], classes: [["skip", "nowrap"]]});
rawMap.set("AmazonSNS", { title: "Amazon Simple Notification Service", th: "Amazon SNS", groups: ["aws"], classes: [["skip", "nowrap"]]});
rawMap.set("AmazonSQS", { title: "Amazon Simple Queue Service", th: "Amazon SQS", groups: ["aws"], classes: [["skip", "nowrap"]]});
rawMap.set("AmazonALB", { title: "Amazon Application Load Balancing", th: "Amazon ALB", groups: ["aws"], classes: [["skip", "nowrap"]]});
rawMap.set("AmazonELB", { title: "Amazon Elastic Load Balancing", th: "Amazon ELB", groups: ["aws"], classes: [["skip", "nowrap"]]});
rawMap.set("AmazonECR", { title: "Amazon Elastic Container Registry", th: "Amazon ECR", groups: ["aws"], classes: [["skip", "nowrap"]]});
rawMap.set("ACM", { title: "#AWS Certificate Manager", groups: ["aws"]});
rawMap.set("AWSKMS", { title: "#AWS Key Management Service", th: "AWS KMS", groups: ["aws"], classes: [["skip", "nowrap"]]});
rawMap.set("AWSSAM", { title: "#AWS Serverless Application Model", th: "AWS SAM", groups: ["aws"], classes: [["skip", "nowrap"]]});
rawMap.set("AWSCLI", { title: "#AWS #CLI", th: "AWS CLI", groups: ["aws"], classes: [["skip", "nowrap"]]});
rawMap.set("AWSCDK", { title: "#AWS Cloud Development Kit", th: "AWS CDK", groups: ["aws"], classes: [["skip", "nowrap"]]});
rawMap.set("AWSCDKCLI", { html: [{tag: "a", href: "#AWSCDK", text: "AWS CDK"}, { text: " "}, {tag: "a", href: "#CLI", text: "CLI" }], th: "AWS CDK CLI", groups: ["aws"], classes: ["nowrap"]});

rawMap.set("ATM", { title: "Automated Teller Machine", groups: []});
rawMap.set("ACID", {title: "Atomicity Consistency Isolation Durability", groups: ["ql"]});
rawMap.set("ACL", {title: "Access Control List", groups: []});
rawMap.set("AES", {title: "Advanced Encryption Standard", groups: [], notes: "#DES"});
rawMap.set("AJAX", {title: "Asynchronous JavaScript And XML", groups: ["javascript"]});
rawMap.set("AKA", {title: "Also Known As", groups: []});
rawMap.set("ANSI", {title: "American National Standards Institute", groups: []});
rawMap.set("AOP", {title: "Aspect Oriented Programming", groups: ["software"]});
rawMap.set("API", {title: "Application Programming Interface", groups: ["software"]});
rawMap.set("ARP", {title: "Address Resolution Protocol", groups: ["protocol"]});
rawMap.set("ASCII", {html: [{text: "American Standard Code"}, {tag: "small", text: " for "}, {text:"Information Interchange"}], groups: []});
rawMap.set("ASIC", {title: "Application-Specific Integrated Circuit", groups: ["electronics"]});
rawMap.set("ATG", {title: "Art Technology Group", groups: ["atg+"], notes: "Oracle Commerce"});
rawMap.set("AWT", {title: "Abstract Window Toolkit", groups: ["java"]});


rawMap.set("BaaS", { title: "Backend as a Service", groups: ["aaS"]});
rawMap.set("BCP", {title: "Business Continuity Plan", groups: []});
rawMap.set("BIOS", {title: "Basic Input/Output System", groups: ["OS", "computer"]});
rawMap.set("BLOB", {title: "Binary Large Object", groups: ["ql"]});
rawMap.set("BMP", {html: [{text: "BitMap Picture "}, {tag: "small", text:"(Microsoft)"}], groups: ["graphics"]});
rawMap.set("BOM", {title: "Bill Of Materials", groups: ["maven"]});
rawMap.set("BYOD", {title: "Bring Your Own Device", groups: []});

rawMap.set("CAD", { title: "Computer-Aided Design", groups: ["design"]});
rawMap.set("CAN", { title: "Controller Area Network", groups: ["vehicle"]});
rawMap.set("CJK", { title: "Chinese Japanese Korean", groups: []});
rawMap.set("CMT", { title: "Container Managed Transaction", groups: ["jta"]});
rawMap.set("CLI", { html: [{text: "Command-Line Interface"}, {tag: "hr", class: "margin-3", text: ""}, {text: "Command-Line Interpreter"}], notes: "#AWSCLI.AWS_CLI #AWSCDKCLI.AWS_CDK_CLI", groups: []});
rawMap.set("CNCF", { title: "Cloud Native Computing Foundation", groups: [], notes: "#K8s", svg: "cncf"});
rawMap.set("CAP", {title: "Consistency | Availability | Partition tolerance", groups: ["ql"]});
rawMap.set("CCPA", {title: "California Consumer Privacy Act", groups: ["GDPR"]});
rawMap.set("CDN", {title: "Content Delivery Network", groups: []});
rawMap.set("CE", {title: "conformité européenne", groups: [], notes: "European Conformity, Fraudulent misuse: \"China Export\""});
rawMap.set("CEO", {title: "Chief Executive Officer", groups: ["role"]});
rawMap.set("CGI", {title: "Computer-Generated Imagery", groups: []});
rawMap.set("CGI1",{title: "Common Gateway Interface", th: "CGI", groups: []});
rawMap.set("CIDR", {title: "Classless Inter-Domain Routing", groups: [], notes: "#IP"});
rawMap.set("CMS1", {title: "Content Management System", th: "CMS", groups: ["CMS"]});
rawMap.set("COO", {title: "Chief Operating Officer", groups: ["role"]});
rawMap.set("CORBA", {title: "Common Object Request Broker Architecture", groups: []});
rawMap.set("CORS", {title: "Cross Origin Resource Sharing", groups: []});
rawMap.set("CPU", {title: "Central Processing Unit", groups: ["processor", "computer"]});
rawMap.set("CQL", {title: "Cassandra Query Language", groups: ["ql"]});
rawMap.set("CRC", {title: "Cyclic Redundancy Check", groups: []});
rawMap.set("CRM", {title: "Customer Relationship Management", groups: []});
rawMap.set("CRT", {title: "Cathode Ray Tube", groups: []});
rawMap.set("CRUD", {title: "Create Read Update Delete", groups: ["ql"]});
rawMap.set("CSP", {title: "Cloud Service Provider", groups: ["cloud"], notes: "#IaaS, #PaaS, #SaaS"});
rawMap.set("CSRF", {title: "Cross-Site Request Forgery", groups: ["vulnerability"]});
rawMap.set("CSS", {title: "Cascading Style Sheet", groups: []});
rawMap.set("CTE", {title: "Common Table Expression", groups: ["ql"]});
rawMap.set("CTO", {title: "Chief Technical Officer", groups: ["role"]});
rawMap.set("CVC", {title: "Centralized Version Control", groups: ["version-control"]});

rawMap.set("DaaS", {title: "Desktop as a Service", groups: ["aaS"]});
rawMap.set("DRaaS", {title: "Disaster Recovery as a Service", groups: ["aaS"]});
rawMap.set("DTAP", { title: "Development, Testing, Acceptance and Production", groups: ["software"]});
rawMap.set("DPI",  { title: "Deep Packet Inspection", groups: ["security"]});
rawMap.set("DVD",  { title: "Digital Video Disk", groups: ["digital-video"]});
rawMap.set("DVR",  { title: "Digital Video Recorder", groups: ["digital-video"]});
rawMap.set("DSL2", { title: "Domain-Specific Language", th: "DSL", groups: ["computer-language"]});
rawMap.set("DBMS", {title: "DataBase Management System", groups: ["db", "ql"]});
rawMap.set("DCL", {title: "Data Control Language", groups: ["sql-subgroup"]});
rawMap.set("DDL", {title: "Data Definition Language", groups: []});
rawMap.set("DDPA", {title: "Dutch Data Protection Authority", groups: ["GDPR"]});
rawMap.set("DES", {title: "Data Encryption Standard", groups: [], notes: "Obsolete, see #AES"});
rawMap.set("DevOps", {title: "Development and Operations", groups: ["software"]});
rawMap.set("DHCP", {title: "Dynamic Host Configuration Protocol", groups: ["protocol"]});
rawMap.set("DIMM", {title: "Dual In-line Memory Module", groups: ["memory", "computer"]});
rawMap.set("DLC", {title: "DownLoadable content", groups: []});
rawMap.set("DLP", {title: "Data Loss Prevention", groups: ["security"]});
rawMap.set("DML", {title: "Data Manipulation Language", groups: ["sql-subgroup"]});
rawMap.set("DMS", {title: "Document Management System", groups: []});
rawMap.set("DNS", {title: "Domain Name System", groups: []});
rawMap.set("DOM", {title: "Document Object Model", groups: [], notes: "#XML, #W3C"});
rawMap.set("DP", {title: "Design Pattern", groups: ["software"]});
rawMap.set("DQL", {title: "Data/Database Query Language", groups: ["ql"]});
rawMap.set("DRY", {title: "Don't repeat yourself", groups: ["design"]});
rawMap.set("DSL", {title: "Digital Subscriber Line", groups: []});
rawMap.set("DTD", {title: "Document Type Definition", groups: ["ml"]});
rawMap.set("DVC", {title: "Distributed Version Control", groups: ["version-control"]});

rawMap.set("ECM", { title: "Enterprise Content Management", groups: ["CMS"]});
rawMap.set("ETF", { title: "Exchange-Traded Fund", groups: []});
rawMap.set("E2E", {title: "End to End", groups: []});
rawMap.set("EAP", {title: "Extensible Authentication Protocol", groups: ["protocol"]});
rawMap.set("ECMA", {title: "European Computer Manufacturers Association", groups: []});
rawMap.set("EDR", {title: "Endpoint Detection and Response", groups: ["security"]});
rawMap.set("EEPROM", {title: "Electrically Erasable Programmable Read-Only Memory", groups: ["memory", "computer"]});
rawMap.set("EPS", {title: "Encapsulated PostScript", groups: ["graphics"]});
rawMap.set("ESG", {title: "Environmental | Social | Governance", groups: []});
rawMap.set("et_al.", {title: "and others", th: "et al.", groups: ["latin"]});
rawMap.set("ETA", {title: "Estimated Time of Arrival", groups: []});

rawMap.set("FaaS", {title: "Function as a Service", groups: ["aaS"]});
rawMap.set("FDD", {title: "Floppy Disk Drive", groups: ["persistence", "computer"]});
rawMap.set("FPGA", {title: "Field-Programmable Gate Array", groups: []});
rawMap.set("FTP", {title: "File Transfer Protocol", groups: ["protocol"]});

rawMap.set("GUID", { title: "Globally Unique IDentifier", groups: ["identifier"], notes: "The same as #UUID"});
 rawMap.set("UUID", { title: "Universally Unique IDentifier", groups: ["identifier"], notes: "The same as #GUID"});
rawMap.set("GA", {title: "General Availability", groups: ["software"]});
rawMap.set("GDPR1", {title: "General Data Protection Regulation", th:"GDPR", classes: ["skip"], groups: ["GDPR"]});
rawMap.set("GIF", {title: "Graphics Interchange Format", groups: ["graphics"]});
rawMap.set("Git", {title: "\"Git\" Linus Torvalds' #DVC", groups: ["version-control"]});
rawMap.set("GML", {title: "Generalized Markup Language", groups: ["ml"], notes: "Extended to #SGML"});
rawMap.set("GPL", {title: "General-Purpose Language", groups: ["computer-language"]});
rawMap.set("GPL2", {title: "General Public License",th: "GPL", groups: ["software"], notes: "#GNU"});
rawMap.set("GPS", {title: "Global Positioning System", groups: []});
rawMap.set("GPU", {title: "Graphics Processing Unit", groups: ["processor", "computer"]});
rawMap.set("GNU", {title: "GNU's Not Unix!", groups: [], svg: "gnu"});
rawMap.set("GQL", {title: "Graph Query Language", groups: ["ql"]});
rawMap.set("GRASP", {title: "General Responsibility Assignment Software Patterns", groups: ["software"], notes: "Controller, creator, indirection, information expert, low coupling, high cohesion, polymorphism, protected variations, pure fabrication"});
rawMap.set("GSM", {html: [{tag:"b", text:"G"}, {text:"lobal "}, {tag:"b", text:"S"}, {text:"ystem for "}, {tag:"b", text:"M"}, {text:"obile Communications"}], groups: ["telecom"]});
rawMap.set("GUI", {title: "Graphic User Interface", groups: [], notes: "#UI"});

rawMap.set("HATEOAS", {title: "Hypermedia as the Engine of Application State", groups: ["restful"]});
rawMap.set("HCMS", {title: "Headless Content Management System", groups: ["CMS"]});
rawMap.set("HDD", {title: "Hard Disk Drive", groups: ["persistence", "computer"]});
rawMap.set("HIPAA", {title: "Health Insurance Portability and Accountability Act", groups: ["GDPR"]});
rawMap.set("HTML", {title: "Hypertext Markup Language", groups: ["ml"]});
rawMap.set("HTTP", {title: "Hypertext Transfer Protocol", groups: ["protocol"], notes: "Stateless", svg: "http"});
rawMap.set("HTTPS", {title: "Hypertext Transfer Protocol Secure", groups: ["protocol"], notes: "Stateless"});
rawMap.set("HVAC", {title: "Heating Ventilation and Air Conditioning", groups: []});

rawMap.set("IDE2", { title: "Integrated Drive Electronics", th: "IDE", groups: ["computer", "pc-interface"], notes: "The same as #PATA", classes: ["skip"]});
 rawMap.set("PATA", { title: "Parallel Advanced Technology Attachment", groups: ["computer", "pc-interface"], notes: "The same as #IDE2"});
rawMap.set("I/O", {title: "Input/Output", groups: []});
rawMap.set("IaaS", {title: "Infrastructure as a Service", groups: ["aaS"]});
rawMap.set("IaC", {title: "Infrastructure as Code", groups: ["cloud"]});
rawMap.set("IAM", {title: "Identity and Access Management", groups: ["security", "aws"]});
rawMap.set("IBAN", {title: "International Bank Account Number", groups: ["banking"]});
rawMap.set("ICMP", {title: "Internet Control Message Protocol", groups: ["protocol"], notes: "#PING"});
rawMap.set("ICS", {title: "Internet Connection Sharing", groups: [], notes: "Ms Windows"});
rawMap.set("IDE", {title: "Integrated Development Environment", groups: ["software"]});
rawMap.set("IEEE", {html: [{text:"Institute "}, {tag: "small", text:"of"}, {text: " Electrical "}, {tag: "small", text:"and"}, {text:" Electronics Engineers"}], groups: []});
rawMap.set("IETF", {title: "Internet Engineering Task Force", groups: ["internet"]});
rawMap.set("iff", {title: "If and only if", groups: [], notes: "↔ ⇔ ≡"});
rawMap.set("IGMP", {title: "Internet Group Management Protocol", groups: ["protocol"]});
rawMap.set("IIFE", {title: "Immediately Invoked Function Expression", groups: ["javascript"]});
rawMap.set("IMAP", {title: "Internet Message Access Protocol", groups: ["protocol"]});
rawMap.set("IMCI", {title: "International Mobile Subscriber Identity", groups: ["telecom"]});
rawMap.set("IMEI", {title: "International Mobile Equipment Identity", groups: ["telecom"]});
rawMap.set("IoT", {title: "Internet of Things", groups: ["internet"]});
rawMap.set("IP", {title: "Internet Protocol", groups: ["protocol"], notes: "#CIDR"});
rawMap.set("IRC", {title: "Internet Relay Chat", groups: []});
rawMap.set("IRQ", {title: "Interrupt ReQuest", groups: []});
rawMap.set("ISBN", {title: "International Standard Book Number", groups: []});
rawMap.set("ISDN", {title: "Integrated Services Digital Network", groups: ["network"]});
rawMap.set("ISO", {title: "International Organization for Standardization", groups: [], svg: "iso"});
rawMap.set("ISP", {title: "Internet Service Provider", groups: []});

rawMap.set("JAX-WS", { title: "Java #API for #XML Web Services", groups: ["java"], classes: ["nowrap"]});
rawMap.set("JIT", { title: "Just-In-Time", groups: ["java", "computing"]});
 rawMap.set("AOT", { title: "Ahead-Of-Time", groups: ["java", "computing"]});
rawMap.set("JAAS", {title: "Java Authentication and Authorization Service", groups: ["java"]});
rawMap.set("JCP", {title: "Java Community Process", groups: ["java"]});
rawMap.set("JDBC", {title: "Java DataBase Connectivity", groups: ["java"]});
rawMap.set("JDK", {title: "Java Development Kit", groups: ["java"]});
rawMap.set("JDMK", {title: "Java Development Management Kit", groups: ["java"]});
rawMap.set("JDWP", {title: "Java Debug Wire Protocol", groups: ["java"]});
rawMap.set("JEP", {title: "#JDK Enhancement Proposal", groups: ["java"]});
rawMap.set("JFC", {title: "Java Foundation Classes", groups: ["java"]});
rawMap.set("JLS", {title: "Java Language Specification", groups: ["java"]});
rawMap.set("JMM", {title: "Java Memory Model", groups: ["java"]});
rawMap.set("JMS", {html: [{text: "Jakarta Messaging "}, {tag: "small", class: "grey", text: "(Java Message Service)"}], groups: ["java"]});
rawMap.set("JMX", {html: [{text: "Java Management E"},{tag: "b", text:"x"},{text: "tensions"}], groups: ["java"]});
rawMap.set("JMXMP", {html: [{text: "Java Management E"},{tag: "b", text:"x"},{text: "tensions Message Protocol"}], groups: ["java"]});
rawMap.set("JNA", {title: "Java Native Access", groups: ["java"]});
rawMap.set("JNDI", {html: [{text: "Java Naming "},{tag: "small", text:"and"},{text: " Directory Interface"}], groups: ["java"]});
rawMap.set("JNI", {title: "Java Native Interface", groups: ["java"]});
rawMap.set("JPA", {html: [{text: "Jakarta Persistence "}, {tag: "small", class:"grey", text:"(Java Persistence #API )"}], groups: ["java"]});
rawMap.set("JPEG", {title: "Joint Photographic Experts Group", groups: ["graphics"]});
rawMap.set("JPQL", {html: [{text: "Jakarta"}, {tag: "small", class:"grey", text:"(Java)"}, { text: " Persistence Query Language"}], groups: ["java", "ql"]});
rawMap.set("JRE", {title: "Java Runtime Environment", groups: ["java"]});
rawMap.set("JSON", {title: "JavaScript Object Notation", groups: ["javascript"], svg: "json"});
rawMap.set("JSR", {title: "Java Specification Request", groups: ["java"]});
rawMap.set("JSP", {title: "Jakarta(Java) Server Pages", groups: ["java"]});
rawMap.set("JSSE", {title: "Java Secure Socket Extension", groups: ["java"]});
rawMap.set("JTA", {html: [{text: "Jakarta Transactions "}, {tag: "small", class:"grey", text:"(Java Transaction #API )"}], groups: ["java"]});
rawMap.set("JUG", {title: "Java User Group", groups: ["java"]});
rawMap.set("JVM", {title: "Java Virtual Machine", groups: ["java"]});
rawMap.set("JVMS", {title: "Java Virtual Machine Specification", groups: ["java"]});
rawMap.set("JWT", {title: "#JSON Web Token", groups: ["security"]});

rawMap.set("K8s", {title: "Kubernetes", groups: ["container-orchestration"], notes: "#CNCF", svg: "K8s"});
rawMap.set("KISS", {html: [{text: "Keep it simple, stupid!"}, {tag: "hr", class: "margin-3"}, {text: "Keep it short & simple"}], groups: ["design"]});
rawMap.set("KTLO", {title: "Keeping The Lights On", groups: []});
rawMap.set("KYC", {title: "Know Your Customer", groups: ["banking"]});

rawMap.set("LED", {title: "Light Emitting Diode", groups: []});
rawMap.set("LIFO", {title: "Last In First Out", groups: ["cache"], notes: "LIFO is a Stack"});
 rawMap.set("FIFO", {title: "First In First Out", groups: ["cache"]});
rawMap.set("LAN", {title: "Local Area Network", groups: ["network"]});
rawMap.set("LDAP", {title: "Lightweight Directory Access Protocol", groups: ["protocol"]});
rawMap.set("LFU", {title: "Least Frequently Used", groups: ["cache"]});
rawMap.set("LRU", {title: "Least Recently Used", groups: ["cache"]});
rawMap.set("LTE", {title: "Long-Term Evolution", groups: ["telecom"], notes: "3.95G"});
rawMap.set("LTE+", {title: "#LTE Advanced", groups: ["telecom"], notes: "LTE-A, 4G+"});
rawMap.set("LTS", {title: "Long-Term Support", groups: ["software"]});
rawMap.set("LWC", {title: "Language of Wider Communication", groups: [], notes: [{tag: "a", href: "referenceBook.html#lingua_franca", text: "Lingua franca"}]});
rawMap.set("LXC", {title: "LinuX Containers", groups: ["OS"]});

rawMap.set("MD", {title: "Markdown Documentation", groups: []});
rawMap.set("MCQ", {title: "Multiple Choice Question", groups: []});
rawMap.set("MCP", {title: "Model Context Protocol", groups: ["ai", "protocol"]});
rawMap.set("MaaS", {title: "Metal as a Service", groups: ["aaS"]});
rawMap.set("MAC", {html: [{text: "Media Access Control "}, {tag: "small", text: "address"}], groups: []});
rawMap.set("MACH", {html: [{text: "Microservices, "}, {tag: "a", href: "#API"}, {text: "-first, Cloud-native and Headless"}], groups: ["architecture"]});
rawMap.set("MAPI", {title: "Messaging Application Programming Interface", groups: [], notes: "Microsoft"});
rawMap.set("MDM", {title: "Mobile Device Management", groups: []});
rawMap.set("MDN", {title: "Mozilla Developer Network", groups: [], notes: "#MSDN"});
rawMap.set("MIME", {title: "Multipurpose Internet Mail Extensions", groups: []});
rawMap.set("MOSFET", {title: "Metal–Oxide–Semiconductor Field-Effect Transistor", groups: ["electronics"]});
rawMap.set("MPEG", {title: "Motion Picture Experts Group", groups: ["graphics"]});
rawMap.set("MSDN", {title: "MicroSoft Developer Network", groups: [], notes: "#MDN"});
rawMap.set("MSRP", {title: "Manufacturer's Suggested Retail Price", groups: [], notes: "List price"});
rawMap.set("mutex", {title: "Mutual exclusion", th: "Mutex", classes: ["skip"], groups: ["concurrency"]});
rawMap.set("MVP", {title: "Minimum Viable Product", groups: []});

rawMap.set("NaaS", {title: "Network as a Service", groups: ["aaS"]});
rawMap.set("NAT", {title: "Network Address Translation", groups: ["network"]});
rawMap.set("NFC", {title: "Near-Field Communication", groups: ["protocol"]});
rawMap.set("NFR", {title: "Non-functional requirement", groups: ["engineering", "system-design"]});
rawMap.set("NFT", {title: "Non-Fungible Token", groups: ["blockchain"]});
rawMap.set("NNTP", {title: "Network News Transport Protocol", groups: ["protocol"]});
rawMap.set("NoSQL", {html: [{text: "Non-relational "}, {tag: "span", class: "tooltip", title : "Database", text: "DB"}, {text: " | Non #SQL | Not only #SQL"}], groups: ["ql"]});
rawMap.set("NTP", {title: "Network Time Protocol", groups: ["protocol"]});

rawMap.set("OSGi", {title: "Open Services Gateway initiative", groups: ["java"]});
rawMap.set("OWASP", {title: "Open Worldwide Application Security Project", groups: ["security"]});
rawMap.set("OAuth", {title: "Open Authorization", groups: ["security", "authorization-protocol"], notes: "Web Authorization Protocol", svg: "Oauth"});
rawMap.set("OCI", {title: "Open Container Initiative", groups: []});
rawMap.set("OCP", {title: "Open/Closed Principle", groups: [], notes: "#SOLID"});
rawMap.set("OCR", {title: "Optical character recognition", groups: []});
rawMap.set("OIDC", {title: "OpenID Connect", groups: ["authentication-protocol"], notes: "An authentication layer on top of the #OAuth 2.0"});
rawMap.set("OLTP", {html: [{text: "On"}, {tag: "b", text: "l"}, {text: "ine Transaction Processing"}], groups: []});
rawMap.set("OOP", {title: "Object Oriented Programming", groups: ["software"]});
rawMap.set("OOTB", {title: "Out of the Box", groups: []});
rawMap.set("OS1", {title: "Operating System",th: "OS", classes: ["skip"], groups: ["OS", "computer"]});
rawMap.set("OSI", {title: "Open Systems Interconnection", groups: []});

rawMap.set("PLC", {title: "Programmable Logic Controller", groups: ["controller"]});
rawMap.set("POJO", {title: "Plain Old Java Object", groups: ["java"]});
rawMap.set("P2P", {title: "Peer-to-Peer", groups: ["network"]});
rawMap.set("PaaS", {title: "Platform as a Service", groups: ["aaS"]});
rawMap.set("PAM", {title: "Pluggable Authentication Module", groups: ["software"]});
rawMap.set("PAN", {title: "Personal Area Network", groups: ["network"]});
rawMap.set("PC", {title: "Personal Computer", groups: ["computer", "processor", "pc-interface", "memory", "video", "persistence", "OS"]});
rawMap.set("PDA", {title: "Personal Digital Assistant", groups: []});
rawMap.set("PDF", {title: "Portable Document Format", groups: ["format"]});
rawMap.set("PECS", {title: "Producer Extends Consumer Super", groups: ["java"]});
rawMap.set("PED", {title: "#PIN Entry Device", groups: []});
rawMap.set("PEMDAS", {title: "Parentheses, Exponents, Multiplication/Division, Addition/Subtraction", groups: []});
rawMap.set("PGP", {title: "Pretty Good Privacy", groups: []});
rawMap.set("PHI", {title: "Protected Health Information", groups: ["GDPR"]});
rawMap.set("PII", {title: "Personally Identifiable Information", groups: ["GDPR"]});
rawMap.set("PIN", {title: "Personal Identification Number", groups: []});
rawMap.set("PING", {title: "Packet InterNet Groper", groups: [], notes: "#ICMP"});
rawMap.set("PMDL", {title: "Promotion Model Definition Language", groups: ["atg+"]});
rawMap.set("PNG", {title: "Portable Network Graphics", groups: ["graphics"]});
rawMap.set("POM", {title: "Project Object Model", groups: ["software", "maven"]});
rawMap.set("POP", {title: "Post Office Protocol", groups: ["protocol"], notes: "POP3"});
rawMap.set("POX", {title: "Plain Old XML", groups: [], notes: "#XML"});
rawMap.set("PPP", {title: "Point-to-Point Protocol", groups: ["protocol"]});
rawMap.set("pub/sub", {title: "Publish-Subscribe", groups: ["design-pattern"]});

rawMap.set("QoS", {title: "Quality of Service", groups: []});

rawMap.set("RED", {title: "Rate, Errors, Duration", groups: ["metrics"]});
rawMap.set("ROI", {title: "Return on Investment", groups: []});
rawMap.set("RGB", {html: [{tag: "span", class: "red", text: "Red"}, {text:" "}, {tag: "span", class: "green", text: "Green"}, {text:" "}, {tag: "span", class: "blue", text: "Blue"}], groups: []});
rawMap.set("RGB", {html: [{tag: "span", class: "red", text: "Red"}, {text:" "}, {tag: "span", class: "green", text: "Green"}, {text:" "}, {tag: "span", class: "blue", text: "Blue"}, {text: " Alfa"}], groups: []});
rawMap.set("RGR", {html: [{tag: "span", class: "red", text: "Red"}, {text:" "}, {tag: "span", class: "green", text: "Green"}, { text: " Refactor"}], groups: ["tdd"]});
rawMap.set("RAM", {title: "Random Access Memory", groups: ["memory", "computer"]});
rawMap.set("RBAC", {title: "Role-Based Access Control", groups: []});
rawMap.set("RDBMS", {title: "Relational DataBase Management System", groups: ["db", "ql"]});
rawMap.set("REST", {title: "Representational State Transfer", groups: ["restful"]});
rawMap.set("RFC", {title: "Request for Comments", groups: ["internet"]});
rawMap.set("RMI", {title: "Remote Method Invocation", groups: ["java"]});
rawMap.set("RoHS", {title: "Restriction of Hazardous Substances", groups: []});
rawMap.set("ROM", {title: "Read Only Memory", groups: ["memory", "computer"]});
rawMap.set("RPC", {title: "Remote Procedure Call", groups: ["software"]});
rawMap.set("RQL", {title: "Repository Query Language", groups: ["ql", "atg+"]});
rawMap.set("RTF", {title: "Rich Text Format", groups: ["format"]});
rawMap.set("RTFM", {title: "Read The Fucking Manual", groups: ["meme"]});
rawMap.set("RTO", {title: "Return to Office", groups: []});

rawMap.set("SHA", {title: "Secure Hash Algorithms", groups: ["security"]});
rawMap.set("SLA", {title: "Service Level Agreement", groups: ["service-level"]});
rawMap.set("SLI", {title: "Service Level Indicator", groups: ["service-level"]});
rawMap.set("SLO", {title: "Service Level Objective", groups: ["service-level"]});
rawMap.set("s/w", {title: "Software", groups: ["software"]});
rawMap.set("SaaS", {title: "Software as a Service", groups: ["aaS"]});
rawMap.set("SAML", {title: "Security Assertion Markup Language", groups: ["ml", "security"]});
rawMap.set("SASL", {title: "Simple Authentication and Security Layer", groups: ["data-security"]});
rawMap.set("SATA", {title: "Serial Advanced Technology Attachment", groups: ["pc-interface", "computer"]});
rawMap.set("SAX", {title: "Simple #API for #XML", groups: [], notes: "Is an alternative to #DOM"});
rawMap.set("SDE", {title: "Software Developer Engineer", groups: ["software"], notes: "The same as #SWE"});
rawMap.set("SDLC", {title: "Software Development Life Cycle", groups: ["software"]});
rawMap.set("SDLC2", {title: "System Design Life Cycle", th: "SDLC", groups: ["system-design"]});
rawMap.set("SEPA", {title: "Single Euro Payments Area", groups: ["banking"]});
rawMap.set("SGML", {title: "Standard Generalized Markup Language", groups: ["ml"]});
rawMap.set("SIMM", {title: "Single In-line Memory Module", groups: ["memory", "computer"]});
rawMap.set("SLF4J", {title: "Simple Logging Facade for Java", groups: ["java"]});
rawMap.set("SMTP", {title: "Simple mail transfer protocol", groups: ["protocol"]});
rawMap.set("SOAP", {html: [{tag: "small", text: "originally an acronym for"}, {text: " Simple Object Access Protocol"}], groups: ["protocol"]});
rawMap.set("SOLID", {title: "#SRP #OCP ; Liskov Substitution; Interface Segregation; Dependency Inversion", groups: ["software"]});
rawMap.set("SPI", {title: "Service Provider Interface", groups: ["java"]});
rawMap.set("SPA", {title: "Single Page Application", groups: ["software"]});
rawMap.set("SQL", {title: "Structured Query Language", groups: ["ql", "sql-subgroup"]});
rawMap.set("SRP", {title: "Single Responsibility Principle", groups: [], notes: "#SOLID"});
rawMap.set("SSD", {title: "Solid State Drive", groups: ["persistence", "computer"]});
rawMap.set("SSH", {title: "Secure Shell Protocol", groups: ["protocol"]});
rawMap.set("SSID", {title: "Service Set IDentifier", groups: ["identifier"]});
rawMap.set("SSL", {title: "Secure Sockets Layer", groups: ["protocol", "cryptographic-protocol"], notes: "Deprecated"});
rawMap.set("SSN", {title: "Social Security Number", groups: []});
rawMap.set("SSO", {title: "Single Sign-On", groups: ["security"]});
rawMap.set("STFU", {title: "Shut The Fuck Up", groups: ["slang"]});
rawMap.set("SVG", {title: "Scalable Vector Graphics", groups: ["graphics"], svg: "svg"});
rawMap.set("SVN", {title: "Apache Subversion. It is #CVC", groups: ["version-control"]});
rawMap.set("SWE", {title: "SoftWare Engineer", groups: ["software"], notes: "The same as #SDE"});

rawMap.set("TX", {title: "Transaction", groups: ["db"]});
rawMap.set("TCL", {title: "Transaction Control Language", groups: ["sql-subgroup"]});
rawMap.set("TCP-IP", {title: "Transmission Control Protocol / Internet Protocol", groups: ["protocol"], notes: "Includes: #IP #HTTP #HTTPS #FTP #DNS #SMTP #UDP"});
rawMap.set("TDD", {title: "Test-Driven Development", groups: ["software", "tdd"]});
rawMap.set("TIFF", {title: "Tagged Image File Format", groups: ["graphics"]});
rawMap.set("TLS", {title: "Transport Layer Security", groups: ["protocol", "cryptographic-protocol"]});

rawMap.set("UoW", {title: "Unit of Work", groups: ["jpa", "dp"]});
rawMap.set("USE", {title: "Utilization, Saturation, Errors", groups: ["metrics"]});
rawMap.set("URI", {title: "Uniform Resource Identifier", groups: ["uniform-resource"], notes: "#URL is a subset of #URI"});
rawMap.set("URL", {title: "Uniform Resource Locator",    groups: ["uniform-resource"], notes: "#URL is a subset of #URI"});
rawMap.set("UDP", {title: "User Datagram Protocol", groups: ["protocol"]});
rawMap.set("UML", {title: "Unified Modeling Language", groups: ["language"]});
rawMap.set("UEFI", {title: "Unified Extensible Firmware Interface", groups: ["OS", "computer"]});
rawMap.set("UI", {title: "User Interface", groups: [], notes: "#GUI"});
rawMap.set("USB", {title: "Universal Serial Bus", groups: ["pc-interface", "computer"]});
rawMap.set("UTF", {title: "Unicode Transformation Format", groups: ["format"]});

rawMap.set("VGA", {title: "Video Graphics Array", groups: ["video", "computer"], notes: "640 × 480"});
rawMap.set("VM", {title: "Virtual Machine", groups: []});
rawMap.set("VoIP", {title: "Voice over Internet Protocol", groups: [], notes: "#IP"});
rawMap.set("VoLTE", {title: "Voice over #LTE", groups: ["telecom"]});
rawMap.set("VPC", {title: "Virtual Private Cloud", groups: ["cloud"]});
rawMap.set("VPN", {title: "Virtual Private Network", groups: ["network"]});

rawMap.set("W3C", {title: "World Wide Web Consortium", groups: ["internet"]});
rawMap.set("WAN", {title: "Wide Area Network", groups: ["network"]});
rawMap.set("WAP", {title: "Wireless Application Protocol", groups: [], notes: "Obsolete"});
rawMap.set("WEP", {title: "Wired Equivalent Privacy", groups: [], notes: "Obsolete, severely flawed security algorithm"});
rawMap.set("WLAN", {title: "Wireless #LAN", groups: ["network"]});
rawMap.set("WORA", {title: "Write Once, Run Anywhere", groups: ["java"], notes: "The same as #WORE"});
rawMap.set("WORE", {title: "Write Once, Run Everywhere", groups: ["java"], notes: "The same as #WORA"});
rawMap.set("WPA", {title: "Wi-Fi Protected Access", groups: [], notes: "WPA2, WPA3"});
rawMap.set("WWW", {title: "World Wide Web", groups: ["internet"]});
rawMap.set("WYSIWYG", {title: "What You See Is What You Get", groups: []});

rawMap.set("XSS", {html: [{tag: "em", class: "fire-brick", text: "Cross"}, {text:"-Site Scripting"}], groups: ["vulnerability"]});
rawMap.set("XHR", {title: "XMLHttpRequest", groups: ["javascript"]});
rawMap.set("XDR",   {html: [{text: "E"}, {tag: "b", text: "x"}, {text: "tended Detection and Response"}], groups: ["security"]});
rawMap.set("XHTML", {html: [{text: "E"}, {tag: "b", text: "x"}, {text: "tensible HyperText Markup Language"}], groups: ["ml"]});
rawMap.set("XML",   {html: [{text: "E"}, {tag: "b", text: "x"}, {text: "tensible Markup Language"}], groups: ["ml"]});
rawMap.set("XMPP",  {html: [{text: "E"}, {tag: "b", text: "x"}, {text: "tensible Messaging and Presence Protocol"}], groups: ["protocol"], notes: "Jabber"});

rawMap.set("YAGNI", {title: "You aren't gonna need it", groups: ["design"]});
rawMap.set("YAML", {html: [{text: "YAML Ain't Markup Language™ "}, {tag: "small", clas: "grey", text: "(Yet Another Markup Language)"}], groups: ["ml"]});

rawMap.set("ZTNA", {title: "Zero Trust Network Access", groups: []});

glossaryGroupMap.set("ml", { text: "#GML -> #SGML -> [ #XML , #HTML -> #XHTML ]; #DTD"});
